const routes = require('next-routes')

module.exports = routes()
    .add('about')
    .add('help')
    .add('contact')
    .add('privacy')
    .add('user')
    .add('edit')
    .add('nearby')
    .add('cuisines', '/truck/cuisine', 'cuisines')
    .add('cuisine', '/truck/cuisine/:value', 'cuisine')
    .add('truck', '/truck/:truckName--id', 'truck')