
// Toggle action
export const TOGGLE_SIGN_IN_MODAL = 'TOGGLE_SIGN_IN_MODAL';
export const TOGGLE_SIGN_UP_MODAL = 'TOGGLE_SIGN_UP_MODAL';
export const TOGGLE_FORGOT_MODAL = 'TOGGLE_FORGOT_MODAL';
export const TOGGLE_ERROR_SIGN_IN_POP_OVER = 'TOGGLE_ERROR_SIGN_IN_POP_OVER';
export const TOGGLE_ERROR_SIGN_UP_POP_OVER = 'TOGGLE_ERROR_SIGN_UP_POP_OVER';
export const TOGGLE_ANNOUNCE_MODAL = 'TOGGLE_ANNOUNCE_MODAL';
export const TOGGLE_SHARE_MODAL = 'TOGGLE_SHARE_MODAL';
export const TOGGLE_CATERING_MODAL = 'TOGGLE_CATERING_MODAL'
// Get user info
export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

// Sign up action
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

// Sign in action
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
// Sign in social 
export const REQUEST_LOGIN_SOCIAL = 'REQUEST_LOGIN_SOCIAL';
export const LOGIN_SOCIAL_SUCCESS = 'LOGIN_SOCIAL_SUCCESS';
export const LOGIN_SOCIAL_ERROR = 'LOGIN_SOCIAL_ERROR';

// Logout action
export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';
export const LOGOUT = 'LOGOUT';

// Update user profile
export const REQUEST_UPDATE_PROFILE = 'REQUEST_UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

//Change password action 
export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

// Search truck action
export const REQUEST_SEARCH_TRUCK = 'REQUEST_SEARCH_TRUCK';
export const SEARCH_TRUCK_SUCCESS = 'SEARCH_TRUCK_SUCCESS';
export const SEARCH_TRUCK_ERROR = 'SEARCH_TRUCK_ERROR';

// Get truck detail action
export const REQUEST_GET_TRUCK_DETAIL = 'REQUEST_GET_TRUCK_DETAIL';
export const GET_TRUCK_DETAIL_SUCCESS = 'GET_TRUCK_DETAIL_SUCCESS';
export const GET_TRUCK_DETAIL_ERROR = 'GET_TRUCK_DETAIL_ERROR';

// Check login when refresh action
export const CHECK_LOGIN = 'CHECK_LOGIN';

// Get truck review action
export const REQUEST_GET_TRUCK_REVIEW = 'REQUEST_GET_TRUCK_REVIEW';
export const GET_TRUCK_REVIEW_SUCCESS = 'GET_TRUCK_REVIEW_SUCCESS';
export const GET_TRUCK_REVIEW_ERROR = 'GET_TRUCK_REVIEW_ERROR';

// Get pairing action
export const REQUEST_GET_PAIRING = 'REQUEST_GET_PAIRING';
export const GET_PAIRING_SUCCESS = 'GET_PAIRING_SUCCESS';
export const GET_PAIRING_ERROR = 'GET_PAIRING__ERROR';

// Get truck menu action
export const REQUEST_GET_TRUCK_MENU = 'REQUEST_GET_TRUCK_MENU';
export const GET_TRUCK_MENU_SUCCESS = 'GET_TRUCK_MENU_SUCCESS';
export const GET_TRUCK_MENU_ERROR = 'GET_TRUCK_MENU_ERROR';

// user post review action
export const REQUEST_POST_REVIEW = 'REQUEST_POST_REVIEW';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_ERROR = 'POST_REVIEW_ERROR';

// user post review action
export const REQUEST_EDIT_REVIEW = 'REQUEST_EDIT_REVIEW';
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
export const EDIT_REVIEW_ERROR = 'EDIT_REVIEW_ERROR';


// Get user review action
export const REQUEST_GET_USER_REVIEW = 'REQUEST_GET_USER_REVIEW';
export const GET_USER_REVIEW_SUCCESS = 'GET_USER_REVIEW_SUCCESS';
export const GET_USER_REVIEW_ERROR = 'GET_USER_REVIEW_ERROR';

// Mark favorite 
export const REQUEST_MARK_FAVORITE = 'REQUEST_MARK_FAVORITE';
export const MARK_FAVORITE_SUCCESS = 'MARK_FAVORITE_SUCCESS';
export const MARK_FAVORITE_ERROR = 'MARK_FAVORITE_ERROR';

// unmark favorite 
export const REQUEST_UNMARK_FAVORITE = 'REQUEST_UNMARK_FAVORITE';
export const UNMARK_FAVORITE_SUCCESS = 'UNMARK_FAVORITE_SUCCESS';
export const UNMARK_FAVORITE_ERROR = 'UNMARK_FAVORITE_ERROR';

// Get user favorite 
export const REQUEST_GET_USER_FAVORITE = 'REQUEST_GET_USER_FAVORITE';
export const GET_USER_FAVORITE_SUCCESS = 'GET_USER_FAVORITE_SUCCESS';
export const GET_USER_FAVORITE_ERROR = 'GET_USER_FAVORITE_ERROR';

//Search activity
export const REQUEST_SEARCH_ACTIVITY = 'REQUEST_SEARCH_ACTIVITY';
export const SEARCH_ACTIVITY_SUCCESS = 'SEARCH_ACTIVITY_SUCCESS';
export const SEARCH_ACTIVITY_ERROR = 'SEARCH_ACTIVITY_ERROR';

// Get activity detail
export const REQUEST_GET_ACTIVITY_DETAIL = 'REQUEST_GET_ACTIVITY_DETAIL';
export const GET_ACTIVITY_DETAIL_SUCCESS = 'GET_ACTIVITY_DETAIL_SUCCESS';
export const GET_ACTIVITY_DETAIL_ERROR = 'GET_ACTIVITY_DETAIL_ERROR';

// Search breweries
export const REQUEST_SEARCH_BREWERY = 'REQUEST_SEARCH_BREWERY';
export const SEARCH_BREWERY_SUCCESS = 'SEARCH_BREWERY_SUCCESS';
export const SEARCH_BREWERY_ERROR = 'SEARCH_BREWERY_ERROR';

// Get brewery detail action
export const REQUEST_GET_BREWERY_DETAIL = 'REQUEST_GET_BREWERY_DETAIL';
export const GET_BREWERY_DETAIL_SUCCESS = 'GET_BREWERY_DETAIL_SUCCESS';
export const GET_BREWERY_DETAIL_ERROR = 'GET_BREWERY_DETAIL_ERROR';

// Mount truck 
export const MOUNT_TRUCK = 'MOUNT_TRUCK';
// Mount brewery
export const MOUNT_BREWERY = 'MOUNT_BREWERY';
//Mount pairing
export const MOUNT_PAIRING = 'MOUNT_PAIRING';
//Mount activity
export const MOUNT_ACTIVITY = 'MOUNT_ACTIVITY';
// Get brewery detail action
export const REQUEST_GET_PAIRING_DETAIL = 'REQUEST_GET_PAIRING_DETAIL';
export const GET_PAIRING_DETAIL_SUCCESS = 'GET_PAIRING_DETAIL_SUCCESS';
export const GET_PAIRING_DETAIL_ERROR = 'GET_PAIRING_DETAIL_ERROR';

//Get search result 
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';

export const REQUEST_GET_NEARBY = 'REQUEST_GET_NEARBY';
export const GET_NEARBY_SUCCESS = 'GET_NEARBY_SUCCESS';
export const GET_NEARBY_ERROR = 'GET_NEARBY_ERROR';
export const MOUNT_NEARBY = 'MOUNT_NEARBY';

// brewery review action types
export const REQUEST_GET_BREWERY_REVIEW = "REQUEST_GET_BREWERY_REVIEW"
export const GET_BREWERY_REVIEW_SUCCESS = "GET_BREWERY_REVIEW_SUCCESS"
export const GET_BREWERY_REVIEW_ERROR = "GET_BREWERY_REVIEW_ERROR"

export const REQUEST_EDIT_BREWERY_REVIEW = "REQUEST_EDIT_BREWERY_REVIEW"
export const EDIT_BREWERY_REVIEW_SUCCESS = "EDIT_BREWERY_REVIEW_SUCCESS"
export const EDIT_BREWERY_REVIEW_ERROR = "EDIT_BREWERY_REVIEW_ERROR"

export const REQUEST_POST_BREWERY_REVIEW = "REQUEST_POST_BREWERY_REVIEW"
export const POST_BREWERY_REVIEW_SUCCESS = "POST_BREWERY_REVIEW_SUCCESS"
export const POST_BREWERY_REVIEW_ERROR = "POST_BREWERY_REVIEW_ERROR"

export const REQUEST_GET_USER_BREWERY_REVIEW = "REQUEST_GET_USER_BREWERY_REVIEW"
export const GET_USER_BREWERY_REVIEW_SUCCESS = "GET_USER_BREWERY_REVIEW_SUCCESS"
export const GET_USER_BREWERY_REVIEW_ERROR = "GET_USER_BREWERY_REVIEW_ERROR"

// Deeplink const action
export const CHANGE_ROUTE = "CHANGE_ROUTE"
export const TOGGLE_DEEP_LINK = "TOGGLE_DEEP_LINK"

// Get suggest truck
export const REQUEST_GET_SUGGEST_TRUCK = "REQUEST_GET_SUGGEST_TRUCK"
export const GET_SUGGEST_TRUCK_SUCCESS = "GET_SUGGEST_TRUCK_SUCCESS"
export const GET_SUGGEST_TRUCK_ERROR = "GET_SUGGEST_TRUCK_ERROR"

//catering const
export const NEXT_STEP = "NEXT_STEP"
export const PREVIOUS_STEP = "PREVIOUS_STEP"

// Get caltering recommened truck
export const REQUEST_GET_RECOMMEND_TRUCK = "REQUEST_GET_RECOMMEND_TRUCK"
export const GET_RECOMMEND_TRUCK_SUCCESS = "GET_RECOMMEND_TRUCK_SUCCESS"
export const GET_RECOMMEND_TRUCK_ERROR = "GET_RECOMMEND_TRUCK_ERROR"

// Send catering request to server
export const REQUEST_CATERING = "REQUEST_CATERING"
export const CATERING_SUCCESS = "CATERING_SUCCESS"
export const CATERING_ERROR = "CATERING_ERROR"


// Get suggest truck
export const REQUEST_GET_SUGGEST_BREWERY = "REQUEST_GET_SUGGEST_BREWERY"
export const GET_SUGGEST_BREWERY_SUCCESS = "GET_SUGGEST_BREWERY_SUCCESS"
export const GET_SUGGEST_BREWERY_ERROR = "GET_SUGGEST_BREWERY_ERROR"

// Search action
export const REQUEST_SEARCH = "REQUEST_SEARCH"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_ERROR = "SEARCH_ERROR"
export const ON_PARAM_CHANGE = "ON_PARAM_CHANGE"

// Mark favorite brewery
export const REQUEST_MARK_FAVORITE_BREWERY = 'REQUEST_MARK_FAVORITE_BREWERY';
export const MARK_FAVORITE_BREWERY_SUCCESS = 'MARK_FAVORITE_BREWERY_SUCCESS';
export const MARK_FAVORITE_BREWERY_ERROR = 'MARK_FAVORITE_BREWERY_ERROR';

// unmark favorite 
export const REQUEST_UNMARK_FAVORITE_BREWERY = 'REQUEST_UNMARK_FAVORITE_BREWERY';
export const UNMARK_FAVORITE_BREWERY_SUCCESS = 'UNMARK_FAVORITE_BREWERY_SUCCESS';
export const UNMARK_FAVORITE_BREWERY_ERROR = 'UNMARK_FAVORITE_BREWERY_ERROR';

// Get user favorite 
export const REQUEST_GET_USER_FAVORITE_BREWERY = 'REQUEST_GET_USER_FAVORITE_BREWERY';
export const GET_USER_FAVORITE_BREWERY_SUCCESS = 'GET_USER_FAVORITE_BREWERY_SUCCESS';
export const GET_USER_FAVORITE_BREWERY_ERROR = 'GET_USER_FAVORITE_BREWERY_ERROR';
